const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PNG } = require('pngjs');
const jsQR = require('jsqr');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'staff/login.html'), 'utf8');
const target = html.match(/class="qr-frame" href="([^"]+)"/)[1];
const modalTarget = html.match(/id="androidDownload"[^>]+href="([^"]+)"/)[1];
const png = PNG.sync.read(fs.readFileSync(path.join(root, 'staff/guard-app-qr.png')));
const decoded = jsQR(new Uint8ClampedArray(png.data), png.width, png.height);
assert.ok(decoded, 'The QR image must actually decode.');
assert.equal(decoded.data, target);
assert.equal(decoded.data, modalTarget);
assert.equal(new URL(decoded.data).pathname, '/downloads/security-agency-management-system-guard.apk');
assert.ok(['https://www.tts-agency.site', 'https://security-agency-management-system-download.vercel.app'].includes(new URL(decoded.data).origin));
assert.doesNotMatch(decoded.data, /app-download|login\.html|#/);
const config = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'));
const headers = config.headers.find(item => item.source === new URL(target).pathname).headers;
assert.ok(headers.some(header => header.key === 'Content-Disposition' && header.value.startsWith('attachment;')));
assert.ok(headers.some(header => header.key === 'Content-Type' && header.value === 'application/vnd.android.package-archive'));
console.log('QR decoding, modal link and Android attachment headers match:', decoded.data);
