const fs=require('node:fs'),path=require('node:path');
const base=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(base,p),'utf8').replace(/^\uFEFF/,''));
const m=Object.fromEntries(read('sonarqube/measures.json').component.measures.map(x=>[x.metric,x.value]));
const gate=read('sonarqube/quality-gate.json').projectStatus;
const first=read('sonarqube/issues-1.json');
const all=[];for(let p=1;p<=Math.ceil(first.total/500);p++)all.push(...read(`sonarqube/issues-${p}.json`).issues);
const open=all.filter(i=>!['CLOSED','RESOLVED'].includes(i.status));
const rows=[['Overall coverage',m.coverage+'%'],['Line coverage',m.line_coverage+'%'],['Covered / measurable lines',(+m.lines_to_cover-m.uncovered_lines)+' / '+m.lines_to_cover],['Uncovered lines',m.uncovered_lines],['Branch coverage',m.branch_coverage+'%'],['Bugs (legacy API)',m.bugs],['Code smells (legacy API)',m.code_smells],['Vulnerabilities (legacy API)',m.vulnerabilities],['Security hotspots',m.security_hotspots],['Duplicated lines',m.duplicated_lines],['Duplication density',m.duplicated_lines_density+'%'],['Reliability / security / maintainability ratings',[m.reliability_rating,m.security_rating,m.sqale_rating].map(v=>({1:'A',2:'B',3:'C',4:'D',5:'E'})[+v]||v).join(' / ')],['Quality gate',gate.status]];
const text=`# SonarQube analysis\n\nActual local analysis: Community Build 26.9.0.129388, scanner 5.0.0.\n\n| Metric | Result |\n|---|---:|\n${rows.map(r=>'| '+r.join(' | ')+' |').join('\n')}\n\nScope: application sources in lib, web and supabase/functions, subject to installed language analyzers. Generated deployment copies (.vercel), build output, downloads, dependencies, assets and test code are excluded. The initial scan included deployment copies and is retained under sonarqube/initial-scan for audit only; its metrics are superseded. JavaScript bundle detection also automatically excludes generated-looking files, as recorded in scanner.log.\n\nJavaScript and TypeScript LCOV imports are confirmed in scanner.log. No Dart analyzer is installed (languages.json), so Dart coverage is standalone and is not part of these Sonar coverage metrics. Sonar uses its own executable-line denominator; these results are separate from native runner percentages and are not coverage of every system language.\n\nThe quality gate returned ${gate.status} with ${gate.conditions.length} evaluated conditions. The evaluated condition concerns new violations only (zero since the prior analysis); this is not an overall-code clearance and does not override the three failed unit tests.\n\nStatic findings are analyzer reports requiring review, not reproduced exploits. The legacy bug/smell/vulnerability categories above differ from the dashboard's MQR security/reliability/maintainability impacts, which can overlap. Zero hotspots does not certify security; this Community Build does not provide all commercial security analysis capabilities.\n\nThere are ${open.length} unresolved exported findings (${all.length} total exported, including historical statuses). The complete issue records are in sonarqube/issues-*.json and the reviewable CSV is sonarqube/issues.csv.\n\nEvidence: scanner.log, scanner.exitcode, measures.json, quality-gate.json, languages.json, server-status.json, hotspots.json and screenshots/SonarQube_*.png.\n`;
fs.writeFileSync(path.join(base,'reports/SonarQube-Analysis.md'),text);
const csv=[['Key','Status','Type','Severity','Rule','Component','Line','Message'],...all.map(i=>[i.key,i.status,i.type,i.severity,i.rule,i.component,i.line,i.message])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');
fs.writeFileSync(path.join(base,'sonarqube/issues.csv'),csv);
const report=path.join(base,'reports/White-Box-Testing-Report.md');
fs.writeFileSync(report,fs.readFileSync(report,'utf8').replace('Actual exported measures are saved in sonarqube/measures.json; see the companion SonarQube analysis report. SonarQube metrics are separate from unit assertions and native coverage.',text.replace('# SonarQube analysis','### Actual analysis results')));
console.log(JSON.stringify({metrics:m,gate,exported:all.length,unresolved:open.length}));

