sonar.projectKey=sentinel-link-whitebox
sonar.projectName=Sentinel Link White-Box Assessment
sonar.projectVersion=1.0.10+11
sonar.sources=lib,web,supabase/functions
sonar.tests=testing/whitebox/unit_tests
sonar.test.inclusions=**/*_test.dart,**/*_test.ts,**/*_test.cjs
sonar.exclusions=**/.vercel/**,**/build/**,web/downloads/**,web/tests/**,**/node_modules/**,**/.env*,**/*_test.ts,**/assets/**,**/icons/**,**/fonts/**
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.scm.exclusions.disabled=true
sonar.javascript.lcov.reportPaths=testing/whitebox/coverage/javascript-normalized.lcov.info,testing/whitebox/coverage/backend.lcov.info
sonar.dart.lcov.reportPaths=testing/whitebox/coverage/dart-normalized.lcov.info
sonar.working.directory=testing/whitebox/sonarqube/.scannerwork

